### ISSUE TITLE
fatal: cannot create directory

### ISSUE THREAD

**Issue by lynxnake** [ardaozkal/PebbleArchive#1]
If I clone the repo, cloning stops at `PebbleAppStore/apps/0/0/007: Q watch`:

    git.exe clone --progress -v "https://github.com/ardaozkal/PebbleArchive" "D:\dev\Pebble_Archive"

    Cloning into 'D:\dev\Pebble_Archive'...
    POST git-upload-pack (175 bytes)
    remote: Counting objects: 94517, done.
    remote: Total 94517 (delta 0), reused 0 (delta 0), pack-reused 94517
    Receiving objects: 100% (94517/94517), 1.11 GiB | 10.94 MiB/s, done.
    Resolving deltas: 100% (17625/17625), done.
    fatal: cannot create directory at 'PebbleAppStore/apps/0/0/007: Q watch': Invalid argument
    warning: Clone succeeded, but checkout failed.
    You can inspect what was checked out with 'git status'
    and retry the checkout with 'git checkout -f HEAD'

**Comment by aveao** [comment]
This seems more like git or windows issue. Try cloning on a linux machine or with cygwin/wsl.

**Comment by CrazyPython** [comment]
[Use the source, Luke!](http://wiki.c2.com/?UseTheSourceLuke)

Take [this line ref](https://github.com/git/git/blob/e83352ef23cca2701953ed3c915f1db49b255a7d/builtin/clone.c#L481) to get started.

I would recommend using a visual debugger (instead of just gdb) to step through the code. Find a way to attach the debugger to the git process. 

Visual Studio and CLion have visual debuggers. You might have to do a build from source using the IDE's interface, though having the source might be enough.
